window.__CONFIG__ = {
  VITE_BACKEND_URL: "__VITE_BACKEND_URL__",
  VITE_MODE: "__VITE_MODE__",
  VITE_COGNITO_CLIENT_ID: "__VITE_COGNITO_CLIENT_ID__",
  VITE_COGNITO_DOMAIN: "__VITE_COGNITO_DOMAIN__"
};