services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    image: backend-image:latest
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      secrets:
        - spotify-frontend-env
    image: frontend-image:latest
    ports:
      - "80:80"

secrets:
  spotify-frontend-env:
    file: frontend/.env
